// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGAHKmTk3LtzHzD7VpQhOtCFeQ3P3WqPs',
    appId: '1:354746480588:web:5460b312c6545628dfcf69',
    messagingSenderId: '354746480588',
    projectId: 'shoe-shop-prm392',
    authDomain: 'shoe-shop-prm392.firebaseapp.com',
    storageBucket: 'shoe-shop-prm392.firebasestorage.app',
    measurementId: 'G-LEP2EMRK0V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdQGc6oRH3_dfvy7INXKmE4O9k65k40WE',
    appId: '1:354746480588:android:cec7e01bc248eb3adfcf69',
    messagingSenderId: '354746480588',
    projectId: 'shoe-shop-prm392',
    storageBucket: 'shoe-shop-prm392.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlstGqOdSKzqJM9iBIYPEHmtemfYf93-0',
    appId: '1:354746480588:ios:ca17fd2167dfb6dadfcf69',
    messagingSenderId: '354746480588',
    projectId: 'shoe-shop-prm392',
    storageBucket: 'shoe-shop-prm392.firebasestorage.app',
    iosBundleId: 'com.example.shoeshopPrm392',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlstGqOdSKzqJM9iBIYPEHmtemfYf93-0',
    appId: '1:354746480588:ios:ca17fd2167dfb6dadfcf69',
    messagingSenderId: '354746480588',
    projectId: 'shoe-shop-prm392',
    storageBucket: 'shoe-shop-prm392.firebasestorage.app',
    iosBundleId: 'com.example.shoeshopPrm392',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGAHKmTk3LtzHzD7VpQhOtCFeQ3P3WqPs',
    appId: '1:354746480588:web:8ef615e85a965e9fdfcf69',
    messagingSenderId: '354746480588',
    projectId: 'shoe-shop-prm392',
    authDomain: 'shoe-shop-prm392.firebaseapp.com',
    storageBucket: 'shoe-shop-prm392.firebasestorage.app',
    measurementId: 'G-WZJP44WSE9',
  );
}
